# Generated by Django 6.0.4 on 2026-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosettings',
            name='min_booking_hours',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
