# Generated by Django 6.0.4 on 2026-04-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_settings', '0002_studiosettings_min_booking_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosettings',
            name='min_notice_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
