# Generated by Django 6.0.4 on 2026-05-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_settings', '0003_studiosettings_min_notice_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosettings',
            name='min_cancellation_notice_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
